### PR TITLE
Support specify the publish file name

### PR DESCRIPTION
**Pull request by ihaiker**

### CODE REVIEW

**Comment by Douile** [comment]
This change would mean when user specifies the `NAME` variable they also need to change it for each target otherwise only 1 artifact will be uploaded which makes me hesitant to add it. We do also need to add documentation for the `NAME` variable.

**Comment by MH4GF** [comment]
> This change would mean when user specifies the NAME variable they also need to change it for each target otherwise only 1 artifact will be uploaded which makes me hesitant to add it.

I think I can use matrix like this in this PR implementation, right?

```
on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            name: windows-amd64
          - target: x86_64-unknown-linux-musl
            name: linux-amd64
          - target: x86_64-apple-darwin
            name: darwin-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          NAME: ${{ matrix.name }}
```

**Comment by ihaiker** [comment]
> > This change would mean when user specifies the NAME variable they also need to change it for each target otherwise only 1 artifact will be uploaded which makes me hesitant to add it.
> 
> I think I can use matrix like this in this PR implementation, right?
> 
> ```
> on:
>   release:
>     types: [created]
> 
> jobs:
>   release:
>     name: release ${{ matrix.target }}
>     runs-on: ubuntu-latest
>     strategy:
>       fail-fast: false
>       matrix:
>         include:
>           - target: x86_64-pc-windows-gnu
>             name: windows-amd64
>           - target: x86_64-unknown-linux-musl
>             name: linux-amd64
>           - target: x86_64-apple-darwin
>             name: darwin-amd64
>     steps:
>       - uses: actions/checkout@v2
>       - name: Compile and release
>         uses: rust-build/rust-build.action@latest
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>           RUSTTARGET: ${{ matrix.target }}
>           EXTRA_FILES: "README.md LICENSE"
>           NAME: ${{ matrix.name }}
> ```

Yes, I want to use it like this

**Comment by Douile** [comment]
> > This change would mean when user specifies the NAME variable they also need to change it for each target otherwise only 1 artifact will be uploaded which makes me hesitant to add it.
> 
> I think I can use matrix like this in this PR implementation, right?
> 
> ```
> on:
>   release:
>     types: [created]
> 
> jobs:
>   release:
>     name: release ${{ matrix.target }}
>     runs-on: ubuntu-latest
>     strategy:
>       fail-fast: false
>       matrix:
>         include:
>           - target: x86_64-pc-windows-gnu
>             name: windows-amd64
>           - target: x86_64-unknown-linux-musl
>             name: linux-amd64
>           - target: x86_64-apple-darwin
>             name: darwin-amd64
>     steps:
>       - uses: actions/checkout@v2
>       - name: Compile and release
>         uses: rust-build/rust-build.action@latest
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>           RUSTTARGET: ${{ matrix.target }}
>           EXTRA_FILES: "README.md LICENSE"
>           NAME: ${{ matrix.name }}
> ```

Yes that is fine. Also while we're at it might be worth renaming NAME to something more descriptive like ARCHIVE_NAME

**Comment by MH4GF** [comment]
@ihaiker can you add documentation for the `ARCHIVE_NAME`  and complete this pull request? This feature would be awesome to me! if you're busy, I'll make another pull request.

**Pull request merged**
